Add vault listings
NFTX-project/nftx-protocol-v2 pull request #10
Opened 2022-03-30 11:22 UTC by tomwade

2022-03-30 11:23 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +import "hardhat/console.sol";
Will drop console logging before merge

2022-03-30 11:24 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +    event ListingFilled();
Event attributes need populating

2022-03-30 11:24 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +	INFTXVaultFactory vaultFactory;
Tabs / spaces

2022-03-30 11:24 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +    function setFloorPrice(uint _minFloorPrice) external {
Need to add Floor access / onlyOwner

2022-03-30 11:34 UTC, 0xCaps reviewed
Some event details...

2022-03-30 11:34 UTC, 0xCaps commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +    event ListingCreated();
`(uint256 listingId, uint256 nftId, address vault, uint256 price, uint256 expires)`

I don't believe we can do an event with all the data so would need to loop through each listing created and emit an event.

2022-03-30 11:34 UTC, 0xCaps commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +    event ListingUpdated();
`(uint256 listingId, uint256 price, uint256 expires)`

2022-03-30 11:34 UTC, 0xCaps commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +    event ListingFilled();
`(uint256 listingId)`

2022-03-31 10:39 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +    event ListingCreated(uint listingId, uint nftId, address vault, uint price, uint expires);
Add amount

2022-03-31 10:39 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +    event ListingFilled(uint listingId);
Add amount

2022-03-31 10:40 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +            // ERC721 validation
Move to internal function

2022-03-31 10:41 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +            // ERC721 validation
Look at ERC165 to determine on-chain proof of implementation

2022-03-31 10:43 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +            require(
Close listing if user no longer owns the NFT

2022-03-31 10:47 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +            } else if (asset == punks) {
Add punk test

2022-05-11 15:07 UTC, 0xCaps requested changes

2022-05-11 15:07 UTC, 0xCaps commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +            }
Possibly remove this block

2022-05-11 15:07 UTC, 0xCaps commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +        require(existingListing.seller != buyer, 'Buyer cannot be seller');
Don't care

2022-05-11 15:07 UTC, 0xCaps commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +        _updateListing721(nftId, vault, listingId, existingListing.price, 0);
Just `delete`

2022-05-11 15:07 UTC, 0xCaps commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +        existingListing.amount = existingListing.amount - amount;
SafeMath sub

2022-05-11 15:11 UTC, 0xCaps commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +    function fillListings(
Consider how we handle fees

2022-05-11 15:41 UTC, tomwade commented
Pre-edits:
<img width="971" alt="v1" src="https://user-images.githubusercontent.com/2588988/167891104-14aacf24-bfe3-43a2-b035-a86d6b2aade5.png">

Post-edits:
<img width="966" alt="v2" src="https://user-images.githubusercontent.com/2588988/167891090-c6748d0f-f0bc-4be5-ad6b-bb8285a0aa9e.png">

2022-05-24 14:54 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +        nftxVaultMintFee[vault] = 0;
Drop mint fee caching

2022-05-24 14:56 UTC, tomwade commented on contracts/solidity/NFTXVaultListingUpgradeable.sol
> +            INFTXFeeDistributor(feeDistributor).distribute(nftxVault.vaultId());
Can we drop this? Gas saves

2022-09-13 19:49 UTC, closed without merging